import { fileURLToPath } from "node:url";

const visitorEntry = new URL("../ui/src/visitor.ts", import.meta.url).pathname;
let canBuildVisitor = false;
try {
	Bun.resolveSync("@ryu/browser-local-ai/data", visitorEntry);
	canBuildVisitor = true;
} catch {
	/* Satellite builds use the checked-in browser artifact. */
}
if (canBuildVisitor) {
	const result = await Bun.build({
		entrypoints: [visitorEntry],
		target: "browser",
		minify: true,
	});
	if (!result.success) {
		throw new AggregateError(result.logs, "Visitor runtime build failed");
	}
	const script = await result.outputs[0].text();
	await Bun.write(
		new URL("./src/visitor-bundle.ts", import.meta.url),
		`// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Generated JavaScript contains template literals.\n// biome-ignore-all format: Generated JavaScript is intentionally emitted as one browser bundle.\n// Generated by sidecar/build.ts. Do not edit.\nexport const visitorScript = ${JSON.stringify(script)};\n`
	);
} else if (process.argv.includes("--runtime-only")) {
	throw new Error(
		"Install the Sites UI workspace dependencies to rebuild its browser runtime"
	);
}
if (!process.argv.includes("--runtime-only")) {
	const result = await Bun.build({
		compile: {
			outfile: fileURLToPath(new URL("./dist/ryu-sites", import.meta.url)),
		},
		entrypoints: [fileURLToPath(new URL("./src/index.ts", import.meta.url))],
	});
	if (!result.success) {
		throw new AggregateError(result.logs, "Sites sidecar build failed");
	}
}
