import { escapeHtml } from "./html.ts";
import { resetCalendarHtml } from "./reset-calendar-template.ts";

export function starterHtml(
	name: string,
	template: string,
	description: string
): string {
	if (template === "reset-calendar") {
		return resetCalendarHtml(name, description);
	}
	const content =
		template === "help-center"
			? `<label for="question">Search articles</label><input id="question" placeholder="Search the help center…"><button id="ask" hidden>Ask a question</button><div id="results"></div><label for="documents">Import knowledge (.txt or .md)</label><input id="documents" type="file" accept=".txt,.md" multiple><p id="status" role="status"></p>`
			: template === "dashboard"
				? `<form id="add"><label for="task">New request</label><input id="task" required maxlength="200" placeholder="What needs doing?"><button>Add request</button></form><ul id="items"></ul><p id="status" role="status"></p>`
				: template === "game"
					? `<p>Find the hidden number between 1 and 100.</p><form id="guess"><label for="number">Your guess</label><input id="number" type="number" min="1" max="100" required><button>Check guess</button></form><p id="status" role="status"></p>`
					: "<section><h2>Made for your next idea</h2><p>Edit this page in Ryu Sites. Save a version to review it, then deploy when it is ready.</p></section>";
	const script =
		template === "help-center"
			? `let docs=[{id:'start',title:'Getting started',text:'Import text and Markdown articles to build a searchable help center.'}];const status=document.getElementById('status');const query=document.getElementById('question');const ask=document.getElementById('ask');RyuSite.capabilities().then(c=>{ask.hidden=!c.answers}).catch(()=>{});ask.addEventListener('click',async()=>{if(!query.value.trim())return;ask.disabled=true;status.textContent='Finding an answer…';try{const answer=await RyuSite.ask(query.value);const p=document.createElement('p');p.textContent=answer.text;const sources=document.createElement('small');sources.textContent=answer.sources.map(s=>'Source '+s.id).join(' · ');document.getElementById('results').replaceChildren(p,sources);status.textContent='Answer grounded in connected knowledge'}catch(error){status.textContent=error.message}finally{ask.disabled=false}});function show(){const results=RyuSite.search(docs,query.value);document.getElementById('results').replaceChildren(...results.map(hit=>{const article=document.createElement('article');const heading=document.createElement('h2');heading.textContent=hit.title;const text=document.createElement('p');text.textContent=hit.excerpt;article.append(heading,text);return article}));status.textContent=query.value?results.length+' matching articles':docs.length+' articles ready'}let generation=0;query.addEventListener('input',async()=>{show();const ticket=++generation;try{const capabilities=await RyuSite.capabilities();if(capabilities.mode==='connected'&&capabilities.knowledge&&query.value.trim()){status.textContent='Searching connected knowledge…';const hits=await RyuSite.retrieve(query.value);if(ticket!==generation)return;document.getElementById('results').replaceChildren(...hits.map(hit=>{const article=document.createElement('article');const p=document.createElement('p');p.textContent=hit.text;const citation=document.createElement('small');citation.textContent='Source '+hit.id;article.append(p,citation);return article}));status.textContent=hits.length+' matching sources'}}catch(error){if(ticket===generation)status.textContent=error.message}});document.getElementById('documents').addEventListener('change',async event=>{try{for(const file of event.target.files){if(file.size>100000)throw Error('Each article must be under 100 KB');if(docs.length>=100)throw Error('Article limit reached');docs.push({id:crypto.randomUUID(),title:file.name,text:await file.text()})}show();await RyuSite.local('knowledge').set('documents',docs)}catch(error){status.textContent=error.message}});RyuSite.local('knowledge').get('documents').then(saved=>{if(Array.isArray(saved))docs=saved;show()}).catch(()=>{show();status.textContent+=' · storage unavailable in sandbox preview'});`
			: template === "dashboard"
				? `let items=[];const status=document.getElementById('status');const store=RyuSite.local('requests');function show(){document.getElementById('items').replaceChildren(...items.map(item=>{const li=document.createElement('li');li.textContent=item;return li}))}document.getElementById('add').addEventListener('submit',async event=>{event.preventDefault();const input=document.getElementById('task');items.push(input.value);input.value='';show();try{await store.set('items',items);status.textContent='Saved in this browser'}catch(error){status.textContent='Preview only: '+error.message}});store.get('items').then(saved=>{if(Array.isArray(saved))items=saved;show()}).catch(()=>{});`
				: template === "game"
					? `const target=1+Math.floor(Math.random()*100);let attempts=0;document.getElementById('guess').addEventListener('submit',event=>{event.preventDefault();attempts++;const value=Number(document.getElementById('number').value);document.getElementById('status').textContent=value===target?'Found it in '+attempts+' guesses!':value<target?'Try a higher number.':'Try a lower number.'});`
					: "";
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(name)}</title><style>:root{color-scheme:light dark;font-family:system-ui,sans-serif}body{margin:0;background:light-dark(#fafafa,#171717);color:light-dark(#171717,#fafafa)}main{max-width:760px;margin:0 auto;padding:64px 24px}header{border-bottom:1px solid #8885;padding-bottom:32px;margin-bottom:32px}h1{font-size:clamp(32px,6vw,56px);letter-spacing:-.04em;line-height:1.1}h2{font-size:20px}p{line-height:1.7;opacity:.8}label{display:block;font-size:14px;margin:24px 0 8px}input{box-sizing:border-box;width:100%;padding:14px;border:1px solid #8886;border-radius:8px;background:transparent;color:inherit;font:inherit}button{margin-top:12px;border:0;border-radius:8px;padding:12px 20px;background:#0099ff;color:#fff;font:inherit;cursor:pointer}article,li{padding:16px 0;border-bottom:1px solid #8884}:focus-visible{outline:2px solid #0099ff;outline-offset:3px}footer{margin-top:48px;font-size:12px;opacity:.6}</style></head><body><main><header><small>Built with Ryu Sites</small><h1>${escapeHtml(name)}</h1><p>${escapeHtml(description || "A place for useful ideas.")}</p></header>${content}<footer>Your data stays in this browser unless you explicitly connect a service.</footer></main><script src="/_ryu/runtime.js"></script><script>${script}</script></body></html>`;
}
