import { expect, test } from "@playwright/test";

test("Sites create, save, deploy, local persistence, domain state and revoke", async ({ page, context }) => {
 const errors: string[]=[];
 page.on("pageerror",error=>errors.push(error.message));
 await page.goto("http://127.0.0.1:8421");
 await page.getByRole("button",{name:"New site",exact:true}).click();
 const dialog=page.getByRole("dialog");
 await dialog.getByLabel("Site name",{exact:true}).fill("Northstar Knowledge");
 await dialog.getByLabel("URL name",{exact:true}).fill(`northstar-${Date.now()}`);
 await dialog.getByLabel("Description",{exact:true}).fill("Find clear answers in your team's guides.");
 await dialog.getByRole("button",{name:"Create site",exact:true}).click();
 await expect(page.getByText("Describe your website",{exact:true})).toBeVisible();
 const preview=page.frameLocator('iframe[title="Website preview"]');
 await expect(preview.getByRole("heading",{name:"Northstar Knowledge"})).toBeVisible();
 await preview.getByLabel("Search articles").fill("import");
 await expect(preview.getByRole("heading",{name:"Getting started"})).toBeVisible();
 await page.screenshot({path:"../../../docs/proof/sites-runtime-builder.png",fullPage:true});
 await page.getByRole("button",{name:"Save version",exact:true}).click();
 await expect(page.getByText("Version saved. The deployed version has not changed.")).toBeVisible();
 await page.getByRole("button",{name:"Deploy version",exact:true}).click();
 const link=page.getByRole("link").filter({hasText:'.localhost:8422'});
 await expect(link).toBeVisible();
 const address=await link.getAttribute('href');
 if(!address)throw Error('Visitor URL missing');
 const visitor=await context.newPage();
 await visitor.goto(address);
 await expect(visitor.getByRole("heading",{name:"This site is private"})).toBeVisible();
 await page.getByRole("button",{name:"Settings",exact:true}).click();
 await page.getByRole("combobox",{name:"Who can visit"}).click();
 await page.getByRole("option",{name:"Anyone on the internet"}).click();
 await page.getByRole("button",{name:"Save settings",exact:true}).click();
 await expect(page.getByRole("combobox",{name:"Who can visit"})).toContainText("Anyone on the internet");
 await visitor.reload();
 await expect(visitor.getByRole("heading",{name:"Northstar Knowledge"})).toBeVisible();
 await visitor.locator('#documents').setInputFiles({name:"refunds.md",mimeType:"text/markdown",buffer:Buffer.from("Refund policy: customers can request a refund within 30 days.")});
 await expect(visitor.getByRole("status")).toContainText("2 articles ready");
 await visitor.getByLabel("Search articles").fill("refund");
 await expect(visitor.getByRole("heading",{name:"refunds.md"})).toBeVisible();
 await visitor.reload();
 await visitor.getByLabel("Search articles").fill("refund");
 await expect(visitor.getByText("Refund policy: customers can request a refund within 30 days.")).toBeVisible();
 await visitor.screenshot({path:"../../../docs/proof/sites-runtime-visitor.png",fullPage:true});
 await page.getByPlaceholder("help.example.com").fill(`help-${Date.now()}.northstar.example`);
 await page.getByRole("button",{name:"Add domain",exact:true}).click();
 await expect(page.getByText("pending dns",{exact:true})).toBeVisible();
 await page.screenshot({path:"../../../docs/proof/sites-runtime-settings.png",fullPage:true});
 await page.getByRole("button",{name:"Analytics",exact:true}).click();
 await expect(page.getByRole("cell").first()).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole("button",{name:"Preview",exact:true}).click();
 await page.screenshot({path:"../../../docs/proof/sites-runtime-mobile.png",fullPage:true});
 await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);
 await page.emulateMedia({colorScheme:"dark"});
 await page.evaluate(()=>document.documentElement.classList.add('dark'));
 await expect(page.getByRole("button",{name:"All sites",exact:true})).toHaveCSS("color","oklch(0.985 0 0)");
 await page.screenshot({path:"../../../docs/proof/sites-runtime-dark.png",fullPage:true,animations:"disabled"});
 await page.setViewportSize({width:1440,height:960});
 await page.getByRole("button",{name:"Settings",exact:true}).click();
 await page.getByRole("button",{name:"Take site offline",exact:true}).click();
 await visitor.reload();
 await expect(visitor.locator('body')).toContainText("Site is not deployed");
 expect(errors).toEqual([]);
});
